# Generated by Django 3.2.2 on 2021-06-25 17:59

from django.db import migrations, models
import keci.models


class Migration(migrations.Migration):

    dependencies = [
        ('keci', '0002_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=keci.models.update_filename),
        ),
    ]
